dockerfile manual but hls not working from cabal install so gonan go for ghcup

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,4 +1,4 @@
-FROM mcr.microsoft.com/devcontainers/base:debian
+FROM mcr.microsoft.com/devcontainers/base:debian-11
 
 ENV LANG=C.UTF-8
 
@@ -24,23 +24,22 @@ RUN apt-get update && \
         zlib1g-dev && \
     rm -rf /var/lib/apt/lists/*
 
-# install cabal
-ARG CABAL_INSTALL=3.14.1.1
-ARG CABAL_INSTALL_RELEASE_KEY=EAF2A9A722C0C96F2B431CA511AAD8CEDEE0CAEF
+ARG CABAL_INSTALL=3.12.1.0
+ARG CABAL_INSTALL_RELEASE_KEY=1E07C9A1A3088BAD47F74A3E227EE1942B0BDB95
 
 RUN set -eux; \
     cd /tmp; \
     ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"; \
-    CABAL_INSTALL_TAR="cabal-install-$CABAL_INSTALL-$ARCH-linux-deb12.tar.xz"; \
+    CABAL_INSTALL_TAR="cabal-install-$CABAL_INSTALL-$ARCH-linux-deb11.tar.xz"; \
     CABAL_INSTALL_URL="https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/$CABAL_INSTALL_TAR"; \
     CABAL_INSTALL_SHA256SUMS_URL="https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/SHA256SUMS"; \
     # sha256 from https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/SHA256SUMS
     case "$ARCH" in \
         'aarch64') \
-            CABAL_INSTALL_SHA256='f763fb2af2bc1ff174b7361a7d51109a585954f87a0e14f86d144f3bce28f7a9'; \
+            CABAL_INSTALL_SHA256='c14e8198407f37f7276c77b5cefef60ee6a929b4c22d7316577ce8e2301a758e'; \
             ;; \
         'x86_64') \
-            CABAL_INSTALL_SHA256='73a463306c771e18ca22c0a9469176ffab0138ec5925adb5364ef47174e1adc5'; \
+            CABAL_INSTALL_SHA256='4f60cf1c72f4ad4d82d668839ac61ae15ae4faf6c4b809395799e8a3ee622051'; \
             ;; \
         *) echo >&2 "error: unsupported architecture '$ARCH'"; exit 1 ;; \
     esac; \
@@ -62,20 +61,20 @@ RUN set -eux; \
     \
     cabal --version
 
-ARG GHC=9.12.2
+ARG GHC=9.10.1
 ARG GHC_RELEASE_KEY=FFEB7CE81E16A36B3E2DED6F2DE04D4E97DB64AD
 
 RUN set -eux; \
     cd /tmp; \
     ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"; \
-    GHC_URL="https://downloads.haskell.org/~ghc/$GHC/ghc-$GHC-$ARCH-deb12-linux.tar.xz"; \
+    GHC_URL="https://downloads.haskell.org/~ghc/$GHC/ghc-$GHC-$ARCH-deb11-linux.tar.xz"; \
     # sha256 from https://downloads.haskell.org/~ghc/$GHC/SHA256SUMS
     case "$ARCH" in \
         'aarch64') \
-            GHC_SHA256='bee95bc91a621d8a2e9a9d86dac28ff839605e87316518dae12c779709bd58f1'; \
+            GHC_SHA256='1db449c445d34779d4deaba22341576f7b512a05b6c2b5cb64f3846d1509714e'; \
             ;; \
         'x86_64') \
-            GHC_SHA256='447ec2fcc773ae9ebc3f39766c719641631274f9b765d7426a8cbe9241677c9f'; \
+            GHC_SHA256='78975575b8125ecf1f50f78b1016b14ea6e87abbf1fc39797af469d029c5d737'; \
             ;; \
         *) echo >&2 "error: unsupported architecture '$ARCH'" ; exit 1 ;; \
     esac; \
@@ -98,39 +97,39 @@ RUN set -eux; \
     "/opt/ghc/$GHC/bin/ghc" --version
 
 # install haskell-language-server
-ARG HLS=2.11.0.0
-ARG HLS_RELEASE_KEY=FFEB7CE81E16A36B3E2DED6F2DE04D4E97DB64AD
-RUN set -eux; \
-    cd /tmp; \
-    ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"; \
-    HLS_URL="https://github.com/haskell/haskell-language-server/releases/download/2.11.0.0/haskell-language-server-2.11.0.0-"; \
-    # sha256 from https://downloads.haskell.org/~ghc/$HLS/SHA256SUMS
-    case "$ARCH" in \
-        'aarch64') \
-            HLS_SHA256='bee95bc91a621d8a2e9a9d86dac28ff839605e87316518dae12c779709bd58f1'; \
-            ;; \
-        'x86_64') \
-            HLS_SHA256='447ec2fcc773ae9ebc3f39766c719641631274f9b765d7426a8cbe9241677c9f'; \
-            ;; \
-        *) echo >&2 "error: unsupported architecture '$ARCH'" ; exit 1 ;; \
-    esac; \
-    curl -sSL "$HLS_URL" -o ghc.tar.xz; \
-    echo "$HLS_SHA256 ghc.tar.xz" | sha256sum --strict --check; \
-    \
-    GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
-    curl -sSL "$HLS_URL.sig" -o ghc.tar.xz.sig; \
-    gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$HLS_RELEASE_KEY"; \
-    gpg --batch --verify ghc.tar.xz.sig ghc.tar.xz; \
-    gpgconf --kill all; \
-    \
-    tar xf ghc.tar.xz; \
-    cd "ghc-$HLS-$ARCH-unknown-linux"; \
-    ./configure --prefix "/opt/ghc/$HLS"; \
-    make install; \
-    \
-    rm -rf /tmp/*; \
-    \
-    "/opt/ghc/$HLS/bin/ghc" --version
+# ARG HLS=2.11.0.0
+# ARG HLS_RELEASE_KEY=588764FBE22D19C4
+# RUN set -eux; \
+#     cd /tmp; \
+#     ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"; \
+#     HLS_URL="https://downloads.haskell.org/~hls/haskell-language-server-$HLS/haskell-language-server-$HLS-$ARCH-linux-ubuntu2004.tar.xz"; \
+#     # sha256 from https://downloads.haskell.org/~hls/haskell-language-server-$HLS/SHA256SUMS
+#     case "$ARCH" in \
+#         'aarch64') \
+#             HLS_SHA256='bee95bc91a621d8a2e9a9d86dac28ff839605e87316518dae12c779709bd58f1'; \
+#             ;; \
+#         'x86_64') \
+#             HLS_SHA256='731afff5832397edaebf74b0b8421752735c4b2a8f753b46fbdd63876d5fcdb1'; \
+#             ;; \
+#         *) echo >&2 "error: unsupported architecture '$ARCH'" ; exit 1 ;; \
+#     esac; \
+#     curl -sSL "$HLS_URL" -o ghc.tar.xz; \
+#     echo "$HLS_SHA256 ghc.tar.xz" | sha256sum --strict --check; \
+#     \
+#     GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
+#     curl -sSL "$HLS_URL.sig" -o ghc.tar.xz.sig; \
+#     gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$HLS_RELEASE_KEY"; \
+#     gpg --batch --verify ghc.tar.xz.sig ghc.tar.xz; \
+#     gpgconf --kill all; \
+#     \
+#     tar xf ghc.tar.xz; \
+#     cd "ghc-$HLS-$ARCH-unknown-linux"; \
+#     ./configure --prefix "/opt/ghc/$HLS"; \
+#     make install; \
+#     \
+#     rm -rf /tmp/*; \
+#     \
+#     "/opt/ghc/$HLS/bin/ghc" --version
 
 
 ENV PATH=/root/.cabal/bin:/root/.local/bin:/opt/ghc/${GHC}/bin:$PATH
